import Nav from "@/components/Nav";
import Header from "@/containers/homepage/Header";

import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    window.scrollTo(0, document.body.scrollHeight);
    window.scrollTo(0, 0);
    window.addEventListener("scroll", function () {
      let nav = document.querySelector(".nav__wrap");
      nav?.classList.toggle("nav--scrolled", window.scrollY > 0);
    });
  }, []);
  return (
    <>
      <Head>
        <title>Rightlabs </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="nav__wrap">
          <Nav />
        </div>
        <Header />
      </main>
    </>
  );
}
